version: '3.5'

services:
  app:
    build:
      context: '.'
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    image: jasonpilz/docker-rails:${IMAGE_VERSION:-latest}
    depends_on:
      - db
    ports:
      - '3000:3000'
    volumes:
      - '.:/var/app'
  db:
    image: postgres:9.6
    volumes:
      - 'postgres_data:/var/lib/postgresql/data'

volumes:
  postgres_data:
